### ISSUE TITLE
Will you get a new release?

### ISSUE THREAD

**Issue by egemenzeytinci** [OpenIDEA-YunanUniversity/ycimpute#11]
I've added some codes about categorical prediction in recent months. :) But of course I can't use it in the package right now. Will you get a new release? I would love to install the package with `pip install ycimpute` and use for categorical prediction.

**Comment by egemenzeytinci** [comment]
As far as I can see, you have removed the categorical prediction. I also can't see my contribution. I can't understand why.

**Comment by HCMY** [comment]
yup, I have not release latest version yet, cause..you know..I have a little busy these days and upcomming days too , sorry~
but, if you don't mind.  it would be better that clone project and using 'python setup.py install' instead

**Comment by egemenzeytinci** [comment]
> yup, I have not release latest version yet, cause..you know..I have a little busy these days and upcomming days too , sorry~
> but, if you don't mind. it would be better that clone project and using 'python setup.py install' instead

Thanks for information. If you have time, can you please look at PR?
