### ISSUE TITLE
Problem running sample code

### ISSUE THREAD

**Issue by sundusabrar** [OpenIDEA-YunanUniversity/ycimpute#5]
Hi. I have setup the library using pip and have managed to write down a simple test for MICE imputation as you have suggested in your docs. But I can not seem to get it to run. I am running the code in Pycharm 3.3 IDE in Ubuntu 17.10.

Here is my console output:

<Connected to pydev debugger (build 173.4301.16)
/home/sundus/.local/lib/python2.7/site-packages/pandas/_libs/__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
/home/sundus/.local/lib/python2.7/site-packages/pandas/__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (hashtable as _hashtable,
/home/sundus/.local/lib/python2.7/site-packages/pandas/core/dtypes/common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib
/home/sundus/.local/lib/python2.7/site-packages/pandas/core/util/hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import hashing, tslib
/home/sundus/.local/lib/python2.7/site-packages/pandas/core/indexes/base.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, index as libindex, tslib as libts,
/home/sundus/.local/lib/python2.7/site-packages/pandas/core/tools/datetimes.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs.tslibs.strptime import array_strptime
/home/sundus/.local/lib/python2.7/site-packages/pandas/tseries/frequencies.py:24: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs.tslibs.frequencies import (  # noqa
/home/sundus/.local/lib/python2.7/site-packages/pandas/core/indexes/datetimelike.py:28: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs.period import Period
/home/sundus/.local/lib/python2.7/site-packages/pandas/core/sparse/array.py:33: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.sparse as splib
/home/sundus/.local/lib/python2.7/site-packages/pandas/core/window.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.window as _window
/home/sundus/.local/lib/python2.7/site-packages/pandas/core/groupby.py:68: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import lib, groupby as libgroupby, Timestamp, NaT, iNaT
/home/sundus/.local/lib/python2.7/site-packages/pandas/core/reshape/reshape.py:31: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as _algos, reshape as _reshape
/home/sundus/.local/lib/python2.7/site-packages/pandas/io/parsers.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.parsers as parsers
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._conv import register_converters as _register_converters
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .. import h5g, h5i, h5o, h5r, h5t, h5l, h5p
Traceback (most recent call last):
  File "/home/sundus/Documents/pycharm-professional-2017.3.3/pycharm-2017.3.3/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/home/sundus/Documents/pycharm-professional-2017.3.3/pycharm-2017.3.3/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/sundus/Documents/pycharm-professional-2017.3.3/pycharm-2017.3.3/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/sundus/PycharmProjects/untitled/test_ycimpute.py", line 6, in <module>
    from ycimpute.imputer.mice import MICE
  File "/home/sundus/.local/lib/python2.7/site-packages/ycimpute/imputer/__init__.py", line 2, in <module>
    from ..unsupervised.expectation_maximization import EM
  File "/home/sundus/.local/lib/python2.7/site-packages/ycimpute/unsupervised/__init__.py", line 2, in <module>
    from .expectation_maximization import EM
  File "/home/sundus/.local/lib/python2.7/site-packages/ycimpute/unsupervised/expectation_maximization.py", line 2, in <module>
    from ..utils.tools import Solver
  File "/home/sundus/.local/lib/python2.7/site-packages/ycimpute/utils/tools.py", line 12
    fill_method: object = "zero",
               ^
SyntaxError: invalid syntax

Process finished with exit code 1>

**Comment by HCMY** [comment]
Hi! I‘m sorry to reply you until now.  It seems like you're using Python2.7. ’Could you send you code to me? It would be better you put your code here, or you can send me via my e-mail address on my Github. Thanks.
