### ISSUE TITLE
getting LinAlgError: Singular matrix trying show.analysiser

### ISSUE THREAD

**Issue by bacloud14** [OpenIDEA-YunanUniversity/ycimpute#6]
My data is stadarized numeric and the target is binary.
Before trying a logistic regression on my data, I want to choose the best imputation method, then I filtered on rows with no NaNs, made another one with the same shape with NaNs in random positions, and proceeded with show.analysiser 
Data sampling:
`train_data_without_na = train_data_without_na.head(10000)
train_data_without_na_ = train_data_without_na.copy(deep=True)
home_services_full = train_data_without_na.as_matrix()

np.random.seed(100)
import random

def add_random_na(row):
    vals = row.values
    for _ in range(random.randint(0,len(vals)-15)):
        i = random.randint(0,len(vals)-1)
        vals[i] = np.nan
    return vals

home_services_missing = train_data_without_na_.apply(add_random_na,axis=1)
home_services_missing = home_services_missing.as_matrix()`

 the problem raises when running:
`import pandas as pd
from ycimpute.utils.shower import show

_result = show.analysiser(missing_X=sample_slice_missing, original_X=sample_slice_full)
pd.DataFrame.from_dict(_result,orient='index')`

`---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
<ipython-input-192-512272b17dcf> in <module>()
      2 from ycimpute.utils.shower import show
      3 
----> 4 _result = show.analysiser(missing_X=sample_slice_missing, original_X=sample_slice_full)
      5 pd.DataFrame.from_dict(_result,orient='index')

X:\ProgramData\Anaconda3\lib\site-packages\ycimpute\utils\shower\show.py in analysiser(missing_X, original_X)
     62 
     63     #######################################################
---> 64     em_X_filled = EM().complete(copy.copy(missing_X))
     65     em_filled_arr = em_X_filled[missing_index]
     66     rmse_em_score = evaluate.RMSE(original_arr,em_filled_arr)

X:\ProgramData\Anaconda3\lib\site-packages\ycimpute\utils\tools.py in complete(self, X)
    246         self._check_missing_value_mask(np.isnan(X))
    247         col_type_dict = self._judge_type(X)
--> 248         X = self.solve(X)
    249         return self.clip(X, col_type_dict)
    250 

X:\ProgramData\Anaconda3\lib\site-packages\ycimpute\unsupervised\expectation_maximization.py in solve(self, X)
     60         theta = -np.inf
     61         for iter in range(self.max_iter):
---> 62             updated_X = self._e_step(mu=mu, sigma=sigma, X=copy.copy(X))
     63             mu, sigma, tmp_theta = self._m_step(updated_X)
     64             for i in range(rows):

X:\ProgramData\Anaconda3\lib\site-packages\ycimpute\unsupervised\expectation_maximization.py in _e_step(self, mu, sigma, X)
     36                 loc_nan = np.isnan(X[sample,:])
     37                 new_mu = np.dot(sigma[loc_nan, :][:, ~loc_nan],
---> 38                                 np.dot(np.linalg.inv(sigma[~loc_nan, :][:, ~loc_nan]),
     39                                        (X[sample, ~loc_nan] - mu[~loc_nan])[:,np.newaxis]))
     40                 nan_count = np.sum(loc_nan)

X:\ProgramData\Anaconda3\lib\site-packages\numpy\linalg\linalg.py in inv(a)
    526     signature = 'D->D' if isComplexType(t) else 'd->d'
    527     extobj = get_linalg_error_extobj(_raise_linalgerror_singular)
--> 528     ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
    529     return wrap(ainv.astype(result_t, copy=False))
    530 

X:\ProgramData\Anaconda3\lib\site-packages\numpy\linalg\linalg.py in _raise_linalgerror_singular(err, flag)
     87 
     88 def _raise_linalgerror_singular(err, flag):
---> 89     raise LinAlgError("Singular matrix")
     90 
     91 def _raise_linalgerror_nonposdef(err, flag):

LinAlgError: Singular matrix`

How can I proceed please?

**Comment by HCMY** [comment]
lol...thanks for your issue, I'll check your question ASAP :)

**Comment by HCMY** [comment]
OK, here is the thing, It would be better if you replace your "Matrix" to "numpy array", Good luck~

**Comment by HCMY** [comment]
With pleasure, anytime!
