### ISSUE TITLE
Categorical feature imputer

### ISSUE THREAD

**Issue by egemenzeytinci** [OpenIDEA-YunanUniversity/ycimpute#9]
I see `RandomForestClassifier` in the `iterforest` module, but I think there is no imputer algorithm for the classification problem. Are you planning to integrate?

**Comment by HCMY** [comment]
Yup, I'm planing to solve this problem these months but not use RF, but i recommand scale data so we can sonsider classification mission as regression (like min-max scale). Thanks for advice:)

**Comment by HCMY** [comment]
By the way, if you are willing to try to solve the problem with the random forest, I really appreciate it.It would be very nice if you contribute this library!

**Comment by egemenzeytinci** [comment]
> By the way, if you are willing to try to solve the problem with the random forest, I really appreciate it.It would be very nice if you contribute this library!

Thank you very much for your reply. I would love to contribute, I will try it!
